// Generates YMF271 lookup tables with the same double-precision math as MAME's
// ymf271.cpp init_tables()/init_envelope(), and emits:
//   ymf_tables.h            (C++ arrays for the fixed-point model)
//   <hexdir>/ymf_*.hex      ($readmemh images for the HDL ROMs)
#include <cstdio>
#include <cmath>
#include <cstdint>
#include <string>
#include <vector>
#include "ymf_mame.h"

static FILE *hx(const std::string &dir, const char *n) { return fopen((dir + "/" + n).c_str(), "w"); }

int main(int argc, char **argv) {
	std::string hexdir = argc > 1 ? argv[1] : ".";
	mame_ymf::ymf271 m;   // builds MAME's own tables
	const double pi = 3.14159265358979323846;

	// ---- quarter-wave tables and exactness check against MAME's full tables
	int q0[256], q1a[256], q1b[256];
	for (int i = 0; i < 256; i++) {
		q0[i] = m.m_lut_waves[0][i];
		double mm = sin(((i * 2) + 1) * pi / 1024);
		q1a[i] = (int16_t)((mm * mm) * 32767);
		q1b[i] = -(int16_t)((mm * mm) * -32768);
	}
	auto qwave = [&](const int *q, int idx) { int k = idx & 511; return k < 256 ? q[k] : q[511 - k]; };
	auto recon = [&](int w, int i) -> int {
		switch (w) {
		case 0: return i < 512 ? qwave(q0, i) : -qwave(q0, i);
		case 1: return i < 512 ? qwave(q1a, i) : -qwave(q1b, i);
		case 2: return qwave(q0, i);
		case 3: return i < 512 ? qwave(q0, i) : 0;
		case 4: return i < 512 ? (((2 * i) & 1023) < 512 ? qwave(q0, 2 * i) : -qwave(q0, 2 * i)) : 0;
		case 5: return i < 512 ? qwave(q0, 2 * i) : 0;
		case 6: return 32767;
		default: return 0;
		}
	};
	int bad = 0;
	for (int w = 0; w < 8; w++) for (int i = 0; i < 1024; i++)
		if (recon(w, i) != m.m_lut_waves[w][i]) { if (bad < 10) printf("wave mismatch w%d i%d mame=%d recon=%d\n", w, i, m.m_lut_waves[w][i], recon(w, i)); bad++; }
	printf("wave reconstruction mismatches: %d\n", bad);

	// ---- envelope step tables (exact MAME expressions)
	int ar_step[64], dc_step[64], d1_step[16][64];
	for (int r = 0; r < 64; r++) {
		ar_step[r] = r < 4 ? 0 : (int)(((double)(255 - 0) / m.m_lut_ar[r]) * 65536.0);
		dc_step[r] = r < 4 ? 0 : (int)(((double)(255 - 0) / m.m_lut_dc[r]) * 65536.0);
		for (int l = 0; l < 16; l++) {
			int decay_level = 255 - (l << 4);
			d1_step[l][r] = r < 4 ? 0 : (int)(((double)(255 - decay_level) / m.m_lut_dc[r]) * 65536.0);
		}
	}
	int lfo_step[256];
	for (int i = 0; i < 256; i++) lfo_step[i] = (int)((((double)256 * m.m_lut_lfo[i]) / 44100.0) * 256.0);
	int plfo_saw[256];
	for (int i = 0; i < 256; i++) {
		double f = ((i % 128) * 1.0) / 127.0;
		double v = i < 128 ? f : f - 1.0;
		plfo_saw[i] = (int)lround(v * 256.0);
	}
	static const double cents[8] = { 0, 3.378, 5.0646, 6.7495, 10.1143, 20.1699, 40.1076, 79.307 };
	int pm_k[8];
	for (int i = 0; i < 8; i++) pm_k[i] = (int)lround(65536.0 * log(2.0) * cents[i] / 1200.0);

	int maxar = 0, maxdc = 0;
	for (int r = 0; r < 64; r++) { if (ar_step[r] > maxar) maxar = ar_step[r]; if (dc_step[r] > maxdc) maxdc = dc_step[r]; }
	printf("max ar_step=%d (%d bits) max dc_step=%d\n", maxar, (int)ceil(log2(maxar + 1)), maxdc);
	int maxlfo = 0; for (int i = 0; i < 256; i++) if (lfo_step[i] > maxlfo) maxlfo = lfo_step[i];
	printf("max lfo_step=%d\n", maxlfo);

	// ---- C header
	FILE *h = fopen("ymf_tables.h", "w");
	fprintf(h, "// generated by gen_tables.cpp\n#pragma once\n#include <cstdint>\nnamespace ymf_fx { namespace tbl {\n");
	auto arr = [&](const char *name, const int *v, int n) {
		fprintf(h, "static const int %s[%d] = {", name, n);
		for (int i = 0; i < n; i++) fprintf(h, "%s%d", i ? "," : "", v[i]);
		fprintf(h, "};\n");
	};
	arr("q0", q0, 256); arr("q1a", q1a, 256); arr("q1b", q1b, 256);
	arr("ar_step", ar_step, 64); arr("dc_step", dc_step, 64);
	fprintf(h, "static const int d1_step[16][64] = {");
	for (int l = 0; l < 16; l++) { fprintf(h, "%s{", l ? "," : ""); for (int r = 0; r < 64; r++) fprintf(h, "%s%d", r ? "," : "", d1_step[l][r]); fprintf(h, "}"); }
	fprintf(h, "};\n");
	arr("lfo_step", lfo_step, 256); arr("plfo_saw", plfo_saw, 256); arr("pm_k", pm_k, 8);
	arr("env_vol", m.m_lut_env_volume, 256); arr("tl", m.m_lut_total_level, 128); arr("att", m.m_lut_attenuation, 16);
	int modlvl[8] = { 16, 8, 4, 2, 1, 32, 64, 128 }, fblvl[8] = { 0, 1, 2, 4, 8, 16, 32, 64 };
	arr("modlvl", modlvl, 8); arr("fblvl", fblvl, 8);
	fprintf(h, "static const int rks[32][8] = {");
	for (int k = 0; k < 32; k++) { fprintf(h, "%s{", k ? "," : ""); for (int s = 0; s < 8; s++) fprintf(h, "%s%d", s ? "," : "", mame_ymf::RKS_Table[k][s]); fprintf(h, "}"); }
	fprintf(h, "};\n");
	fprintf(h,
		"static inline int qw(const int *q, int idx) { int k = idx & 511; return k < 256 ? q[k] : q[511 - k]; }\n"
		"static inline int16_t wave(int w, int i) {\n"
		"  switch (w) {\n"
		"  case 0: return i < 512 ? qw(q0, i) : -qw(q0, i);\n"
		"  case 1: return i < 512 ? qw(q1a, i) : -qw(q1b, i);\n"
		"  case 2: return qw(q0, i);\n"
		"  case 3: return i < 512 ? qw(q0, i) : 0;\n"
		"  case 4: return i < 512 ? ((((2 * i) & 1023) < 512) ? qw(q0, 2 * i) : -qw(q0, 2 * i)) : 0;\n"
		"  case 5: return i < 512 ? qw(q0, 2 * i) : 0;\n"
		"  case 6: return 32767;\n"
		"  default: return 0; }\n}\n");
	fprintf(h, "}}\n");
	fclose(h);

	// ---- HDL hex images
	FILE *f;
	f = hx(hexdir, "ymf_qwave.hex");     // [9:8]=table (0:q0 1:q1a 2:q1b) [7:0]=index, 16-bit
	for (int t = 0; t < 4; t++) for (int i = 0; i < 256; i++) fprintf(f, "%04X\n", (t == 0 ? q0[i] : t == 1 ? q1a[i] : t == 2 ? q1b[i] : 0) & 0xffff);
	fclose(f);
	f = hx(hexdir, "ymf_envvol.hex");    // 256 x 17 bit
	for (int i = 0; i < 256; i++) fprintf(f, "%05X\n", m.m_lut_env_volume[i]);
	fclose(f);
	f = hx(hexdir, "ymf_tl.hex");        // 128 x 17 bit
	for (int i = 0; i < 128; i++) fprintf(f, "%05X\n", m.m_lut_total_level[i]);
	fclose(f);
	f = hx(hexdir, "ymf_att.hex");       // 16 x 17 bit
	for (int i = 0; i < 16; i++) fprintf(f, "%05X\n", m.m_lut_attenuation[i]);
	fclose(f);
	// envelope step ROM, 2048 x 23 bit: addr[10]=0: d1 table (d1l[9:6], rate[5:0]);
	// addr[10:6]=10000: attack[rate]; 10001: dc[rate]; others 0
	f = hx(hexdir, "ymf_envstep.hex");
	for (int a = 0; a < 2048; a++) {
		int v = 0;
		if (a < 1024) v = d1_step[a >> 6][a & 63];
		else if ((a >> 6) == 16) v = ar_step[a & 63];
		else if ((a >> 6) == 17) v = dc_step[a & 63];
		fprintf(f, "%06X\n", v);
	}
	fclose(f);
	f = hx(hexdir, "ymf_lfostep.hex");   // 256 x 10 bit
	for (int i = 0; i < 256; i++) fprintf(f, "%03X\n", lfo_step[i]);
	fclose(f);
	f = hx(hexdir, "ymf_plfosaw.hex");   // 256 x 10 bit signed
	for (int i = 0; i < 256; i++) fprintf(f, "%03X\n", plfo_saw[i] & 0x3ff);
	fclose(f);
	printf("pm_k:"); for (int i = 0; i < 8; i++) printf(" %d", pm_k[i]); printf("\n");
	printf("att:"); for (int i = 0; i < 16; i++) printf(" %d", m.m_lut_attenuation[i]); printf("\n");
	return 0;
}
